# Workaround for https://github.com/conda-forge/gz-transport-feedstock/pull/68#issuecomment-3112254165
c_compiler_version:     # [osx]
  - 18                  # [osx]
cxx_compiler_version:   # [osx]
  - 18                  # [osx]
