{% set component_name = "sim" %}
{% set repo_name = "gz-" + component_name %}
{% set version = "7_7.6.0" %}
{% set version_package = version.split('_')[1] %}
{% set major_version = version.split('_')[0] %}
{% set name = repo_name + major_version %}
{% set component_version = component_name + major_version %}
{% set cxx_name = "lib" + name %}
{% set python_name = name + "-python" %}

package:
  name: {{ name }}
  version: {{ version_package }}

source:
  - url: https://github.com/gazebosim/gz-sim/archive/refs/tags/gz-sim{{ version }}.tar.gz
    sha256: 872c08cb3cefe4b865daa3454256ba16ac993339bcad4a620930fbb51392c5e3
    patches:
      - standalone_bindings.patch
      - support_protobuf_crosscompilation.patch

build:
  number: 10

outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
        # Used by tests
        - make  # [unix]
        # We need protoc in build for cross-compiling
        - libabseil  # [build_platform != target_platform]
        - libprotobuf  # [build_platform != target_platform]
      host:
        - libgz-cmake3
        - libsdformat13
        - libgz-plugin2
        - libgz-transport12
        - libgz-msgs9
        - libgz-common5
        - libgz-fuel-tools8
        - libgz-gui7
        - libgz-physics6
        - libgz-sensors7
        - libgz-rendering7
        - libgz-utils2
        - libgz-math7
        - libgz-tools2
        - libabseil
        - libprotobuf
        - qt-main
        - tinyxml2
        - xorg-libxfixes  # [linux]

    test:
      commands:
        - test -f ${PREFIX}/include/gz/{{ component_version }}/gz/{{ component_name }}.hh  # [not win]
        - test -f ${PREFIX}/lib/lib{{ name }}.so  # [linux]
        - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\include\\gz\\{{ component_version }}\\gz\\{{ component_name }}.hh exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

  - name: {{ python_name }}
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - swig
        - ninja
        - cmake
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - pybind11-abi                           # [build_platform != target_platform]
        - pytest                                 # [build_platform != target_platform]
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
      host:
        - {{ pin_subpackage(cxx_name, exact=True) }}
        - libgz-common5
        - python
        - pip
        - setuptools
        - pybind11
        - pybind11-abi
        - pytest
        - xorg-libxfixes  # [linux]
        # Workaround for errors of type
        # package libgz-sim7-<..> requires <...>, but none of the providers can be installed
        - libabseil
        - libprotobuf
        - libgz-sensors7
        - libgz-physics6
        - qt-main
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
        - python
    test:
      commands:
        - pip check
      requires:
        - pip
      imports:
        - gz.{{ component_name }}{{ major_version }}

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
        - {{ pin_subpackage(python_name, max_pin='x.x.x') }}
    test:
      imports:
        - gz.{{ component_name }}{{ major_version }}

about:
  home: https://github.com/gazebosim/gz-sim
  license: Apache-2.0
  license_file: LICENSE
  summary: "Open source robotics simulator. The latest version of Gazebo."

extra:
  feedstock-name: {{ repo_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
